Add support for MultipartEncoder
akamai/AkamaiOPEN-edgegrid-python pull request #61
Opened 2022-04-20 16:57 UTC by fifty-50

2022-04-27 08:35 UTC, robertolopezlopez commented
hi @fifty-50 ,

Thank you for taking your time creating this PR. Could you please add any unit tests?

Regards,

Roberto

2022-04-27 08:36 UTC, robertolopezlopez requested changes
Please, add unit tests

2022-04-29 12:42 UTC, fifty-50 commented
Hi @robertolopezlopez, I have added some tests.

2022-05-17 07:25 UTC, robertolopezlopez requested changes

2022-05-17 07:25 UTC, robertolopezlopez commented on akamai/edgegrid/test/test_edgegrid.py
> +import requests_toolbelt
Please, add this as a new dependency in requirements.txt and setup.py

2022-05-17 07:27 UTC, robertolopezlopez commented
I have an extra question @fifty-50 ,

Which is the endpoint that will benefit from this PR? Which is the intended use case? Because we will need to test manually as well before merge :-)

Regards,

Roberto

2022-05-17 13:19 UTC, fifty-50 commented on akamai/edgegrid/test/test_edgegrid.py
> +import requests_toolbelt
added it

2022-05-17 13:20 UTC, fifty-50 commented
Hi @robertolopezlopez, the [/case-management/v3/cases/{caseId}/attachments](https://techdocs.akamai.com/case-mgmt/reference/post-attachments) endpoint accepts multipart request payloads, which can be large in size. Adding support for MultipartEncoder would allow streaming of such large payloads.

HTTPie uses MultipartEncoder for all multipart requests, and so it fails when trying to send any multipart request using EdgeGrid authentication. If MultipartEncoder support is added in the edgegrid-python library, the HTTPie integration will also be able to sign and send multipart requests.

2022-07-22 15:41 UTC, robertolopezlopez commented
Hi @fifty-50 , if you could help me manually test this change, we may merge this branch quickly. Please ping me through webex

2022-08-01 10:00 UTC, robertolopezlopez approved these changes
Hi @fifty-50 ,

Looks great to me , thank you very much for this PR. We will try to release this change and upgrade the dependency in httpie-edgegrid as soon as we can.

Regards,

Roberto

2022-08-01 10:02 UTC, kaush- approved these changes

2022-08-01 10:03 UTC, merged